import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";

import {
  Text,
  Container,
  Center,
  Card,
  CardHeader,
  CardBody,
  CardFooter,
  Flex,
} from "@chakra-ui/react";

const Dashboard: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Flex
            height={"100vh"}
            alignContent={"center"}
            justifyContent={"center"}
          >
            <Center>
              <Card>
                <CardBody>
                  <CardHeader>
                    {hello.data ? hello.data.greeting : "Loading tRPC query..."}
                  </CardHeader>
                </CardBody>
              </Card>
            </Center>
          </Flex>
        </Container>
      </main>
    </>
  );
};

export default Dashboard;
